### ISSUE TITLE
notebook无法import package

### ISSUE THREAD

**Issue by babybear1992** [ryanxiauic/Jupyterhub_setup#1]
按照教程方法在服务器上装了jupyterhub. 打开Notebook后，比如运行`pip show pandas`可以看到package的路径，但是`import pandas`就会显示`no module named pandas`。可能是`conda.sh`这个脚本里面的内容导致了问题？
我试了试
```python
import sys    
sys.path
# 返回如下
['',
 '/opt/anaconda3/envs/py36/lib/python36.zip',
 '/opt/anaconda3/envs/py36/lib/python3.6',
 '/opt/anaconda3/envs/py36/lib/python3.6/lib-dynload',
 '/opt/anaconda3/envs/py36/lib/python3.6/site-packages',
 '/opt/anaconda3/envs/py36/lib/python3.6/site-packages/IPython/extensions',
 '/home/user_xxx/.ipython',
```
问题在于，安装的package在`/opt/anaconda3/py36/site-packages`下，把这个路径添加到sys.path就可以解决问题。

**Comment by ryanxiauic** [comment]
额,你的package是装在哪个环境里的？

**Comment by ryanxiauic** [comment]
注意你的package是装在py36下的，得和jupyter kernel一致哦。看看 jupyter kernelspec list。

**Comment by babybear1992** [comment]
嗯嗯，后来单独写了两个安装pkg的脚本，分别激活了py36和py27两个环境后，进行安装，问题解决了。

**Comment by ryanxiauic** [comment]
好的~ 谢谢你~ 这是我收到的第一个issue~
